[workspace]
members = ["quincy", "quincy-client", "quincy-server", "quincy-gui"]
resolver = "2"

[workspace.package]
version = "0.16.0"
authors = ["Jakub Kubík <jakub.kubik.it@protonmail.com>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
edition = "2021"
rust-version = "1.80"
homepage = "https://github.com/quincy-rs/quincy"
repository = "https://github.com/quincy-rs/quincy"
keywords = ["vpn", "quic", "tunnel", "networking", "tokio"]
categories = ["command-line-utilities", "network-programming"]

[workspace.dependencies]
# Quinn
quinn = { version = "^0.11.8", default-features = false, features = [
    "log",
    "platform-verifier",
    "runtime-tokio",
    "rustls-aws-lc-rs",
] }

# Interfaces and networking
tun-rs = { version = "=2.1.0", features = [
    "async_tokio",
] } # pinned audited version
socket2 = "^0.6.0"
bytes = "^1.4"
ipnet = { version = "^2.7", features = ["serde"] }

# Tokio
tokio = { version = "^1.44.2", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "io-util",
    "signal",
] }
dashmap = "^6"
futures = "^0.3.17"
async-trait = "^0.1.77"

# Configuration
figment = { version = "^0.10.8", features = ["toml", "env"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"

# TLS
rustls = { version = "^0.23.18", default-features = false, features = [
    "aws-lc-rs",
] }
rustls-pemfile = "^2.0"

# Authentication
argon2 = "^0.5.0"
rpassword = "^7.2"
rand_core = { version = "^0.6.4", features = ["getrandom"] }

# Tracing/Logging
tracing = { version = "^0.1.37", features = ["release_max_level_info"] }
tracing-subscriber = { version = "^0.3.20", features = ["env-filter", "ansi"] }
nu-ansi-term = "^0.50.0"

# Utils
anyhow = "^1.0"
clap = { version = "^4.1", features = ["derive"] }

# GUI
iced = { version = "^0.13.0", features = ["tokio", "advanced", "highlighter", "multi-window"] }

# Alloc
jemallocator = { version = "0.5" }

# WinTun
wintun-bindings = { version = "0.7.31", features = ["verify_binary_signature"] }

# Dev dependencies
rstest = "^0.25.0"
etherparse = "^0.18.0"
tracing-test = { version = "^0.2.4", features = ["no-env-filter"] }

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
panic = "abort"
