ignore:
  # Ignore all app entrypoints because they are not unit/integration tested
  - "**/src/bin/*"
  - "**/src/main.rs"
  # Ignore all network related code because it cannot be unit/integration tested in CI
  - "quincy/src/network"
  # Ignore GUI code because it cannot be unit/integration tested in CI
  - "quincy-gui"
  # Command utilities
  - "quincy/src/utils"
